### ISSUE TITLE
Wacom Intuos BT S - not detected, Linux Mint 21.1

### ISSUE THREAD

**Issue by mateimm** [linuxwacom/libwacom#627] opened 2024-01-19 14:06 UTC
- **Device name**: Wacom Intuos BT S
- **Device model identifier**: CTL-4100WL
- **libwacom version**: -- not sure how I could check that

- [X ] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

# Bug description

Hello,

I am having issues with my tablet 
```
Name=Wacom Intuos BT S
ModelName=CTL-4100WL
```
I have not used it in some time and before today it was working fine.

I can connect it to the Bluetooth but is not detected in the Graphics Tablet application.

I am using a Linux Mint 21.1 OS

Using command `libwacom-list-devices`
 I see it listed as:
```
- { bus: 'bluetooth', vid: '0x056a', pid: '0x0377', name: 'Wacom Intuos BT S' }
- { bus: 'bluetooth', vid: '0x056a', pid: '0x03c6', name: 'Wacom Intuos BT S' }
```

I have checked `$ ll /usr/share/libwacom`
 and I can find my model under the name `intuos-s-p3-wl.tablet`
Looking inside this file I see the above **vid:pid** listed at the DeviceMatch as below:
` DeviceMatch=usb:056a:0376;bluetooth:056a:0377;usb:056a:03c5;bluetooth:056a:03c6`

I am still not sure what's wrong and why it can't be detected.

Any help would be much appreciated.
Thank you,
Matei

**Comment by whot** [comment] 2024-01-22 01:14
`libwacom-list-local-devices` does not show it?

Does it show up with e.g. `libinput record`?

**Comment by whot** [comment] 2024-05-07 06:14
Does it show up with e.g. libinput record?

**Comment by whot** [comment] 2024-09-02 02:14
/close

Closing, can't proceed without any information

**Closed by whot** 2024-09-02 02:14 UTC

**Comment by illya-laifu** [comment] 2024-11-05 22:21
Not sure if this needs to be reopened, or if I need to create a new issue as this one was closed.

But I have the same situation with my tablet of the same model and name, both with USB and Bluetooth.

The tablet is property identified via dmesg:
```
[176709.526664] usb 7-1: USB disconnect, device number 3
[176714.567008] usb 7-1: new full-speed USB device number 4 using xhci_hcd
[176714.731921] usb 7-1: New USB device found, idVendor=056a, idProduct=03c5, bcdDevice= 2.07
[176714.731924] usb 7-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[176714.731926] usb 7-1: Product: Intuos BT S
[176714.731927] usb 7-1: Manufacturer: Wacom Co.,Ltd.
[176714.731928] usb 7-1: SerialNumber: 2DK00S2006429
```

However this device is not listed using `libwacom-list-local-devices`, `libinput record`, nor it appears in `/proc/bus/input/devices`.

**Comment by illya-laifu** [comment] 2024-11-06 16:10
Poked around a bit and read a few existing  issues, I got it working but I am not entirely sure it's correct.

The issue was that the tablet was running in "PC Mode" as indicated by the ID pair: `056a:03c5`. Holding down buttons documented [here](https://github.com/linuxwacom/xf86-input-wacom/wiki/Known-Issues#issue-my-wacom-intuos-ctl-4100-or-ctl-6100-seems-to-be-miscalibrated-and-has-a-dimmed-status-led), switches it to the android mode. It can be seen in lsusb as indicated by the change of the vendor ID in the ID  pair: `2d1f:03c5`. 

Switching to the android mode also allows the device to be seen via `libwacom-list-local-devices`
```yaml
devices:
- name: 'Wacom Intuos BT S (Android Mode)'
  bus: 'usb'
  vid: '0x2d1f'
  pid: '0x03c5'
  nodes: 
  - /dev/input/event260: 'Wacom Co.,Ltd. Intuos BT S'
  styli:
   - id: 0x862
     name: 'Intuos Pen'
     type: 'general'
     axes: ['x', 'y' , 'distance', 'pressure']
     buttons: 2
     erasers: []
```

My question is - shouldn't this tablet be seen in both modes, or just the PC mode and not the android mode?

**Comment by whot** [comment] 2024-11-06 20:38
> My question is - shouldn't this tablet be seen in both modes, or just the PC mode and not the android mode?

iirc the android mode of the tablet does not work that well under linux because the device behaves (subtly?) different, which is probably why it exists in the first place. libwacom could detect it in this mode (it's just a static description of the device after all) but that won't help with all the other issues that follow on. So IMO it's not worth it.

**Comment by illya-laifu** [comment] 2024-11-06 21:56
Right, but the question still remains of why the regular mode is not detected.

Both ID sets are present in the output of `libwacom-list-devices` and yet only one (android) is detected.

## Android mode:

### dmesg:

```
[200183.519435] usb 7-1: new full-speed USB device number 19 using xhci_hcd
[200183.683355] usb 7-1: New USB device found, idVendor=056a, idProduct=03c5, bcdDevice= 2.07
[200183.683358] usb 7-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[200183.683360] usb 7-1: Product: Intuos BT S
[200183.683361] usb 7-1: Manufacturer: Wacom Co.,Ltd.
[200183.683362] usb 7-1: SerialNumber: 2DK00S2006429
```

### libwacom

```bash
> libwacom-list -local-devices
devices:
- name: 'Wacom Intuos BT S (Android Mode)'
  bus: 'usb'
  vid: '0x2d1f'
  pid: '0x03c5'
...
libwacom-list-devices  | rg "2d1f.*03c5"
- { bus: 'usb',       vid: '0x2d1f', pid: '0x03c5', name: 'Wacom Intuos BT S (Android Mode)', uniq: '(null)' }
```
## Standard mode

### dmesg
```
[200702.789683] usb 7-1: New USB device found, idVendor=056a, idProduct=03c5, bcdDevice= 2.07
[200702.789687] usb 7-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[200702.789688] usb 7-1: Product: Intuos BT S
[200702.789689] usb 7-1: Manufacturer: Wacom Co.,Ltd.
[200702.789690] usb 7-1: SerialNumber: 2DK00S2006429
```

### libwacom

```bash
> libwacom-list-local-devices
Failed to find any devices known to libwacom.
...
> libwacom-list-devices  | rg "056a.*03c5"
- { bus: 'usb',       vid: '0x056a', pid: '0x03c5', name: 'Wacom Intuos BT S', uniq: '(null)' }
```

**Comment by whot** [comment] 2024-11-07 01:36
Can you try #825 please? Let's see what it actually sees, the code for this is simple enough that there's no good reason it should miss the device (assuming working udev and whatnot)

**Comment by illya-laifu** [comment] 2024-11-07 20:55
No luck here - there is no extra output. I've peppered the code with fprints to help me with debugging, and , I believe, that pointed me into the right direction.

While the device is in Android mode, `/dev/input/` has two extra devices, compared  to the Standard mode. So there is nothing wrong with the libwacom, it's just that my OS does not detect those devices.


Since this is not relevant to libwacom, would you be able to point me to somewhere this is related to?

**Comment by whot** [comment] 2024-11-07 21:33
Oh, I just noticed: `Failed to find any devices known to libwacom.`. If that's all you get none of your your devices have `ID_INPUT_TABLET` set which points at a broken udev install. Not sure how and why this is only an issue in the PC mode.

If the tablet was simply missing from libwacom you should see a `is a tablet but not supported by libwacom` message. Are you on Mint like the original reporter?

**Comment by illya-laifu** [comment] 2024-11-07 22:17
I am not on Mint, but I think I understand why you are asking this question - kernel modules, which leads me to a solution (?) that immediately raises a few questions. I will list them out, just in case. 

1. Loading wacom kernel module via `modprobe` fails silently and no module is loaded, but `insmod` with the absolute path of the module listed from `modinfo wacom` works. (This could possibly be caused by my odd Linux installation, but I doubt)
2. Output of the `usb-devices` shows Wacom tablets using usbhid as their driver, shouldn't that be wacom?
3. The fact that the Android mode worked without the module while the standard one didn't is perplexing.

**Comment by whot** [comment] 2024-11-07 22:28
> The fact that the Android mode worked without the module while the standard one didn't is perplexing.

I'm guessing the android mode is explicitly designed to work without the wacom drivers since it's likely android devices do not ship those. Check the `DRIVER` udev property on the device's hid node, that should list `DRIVER=wacom`. `usb-devices` seems to only list the driver as seen by the usb subsystem which is a level too deep.

Either way, this definitely looks like a local issue now, doubly so since you're using a different system than the original reporter. If you have an "odd Linux installation" then that is something you'll need to fix locally, it's too hard guessing what specific combination can trigger this particular issue.
