### ISSUE TITLE
Support for Graphire 2?

### ISSUE THREAD

**Issue by terzag** [linuxwacom/libwacom#3] opened 2017-05-24 15:48 UTC
Hello,
Using Ubuntu GNOME 17.04 (GNOME 3.24). I have an old USB Wacom Graphire 2 tablet which works fine on Ubuntu but is not recognized by the system Wacom Tablet settings tool. Looking at the files here, I see that there are .tablet profiles for Graphire, Graphire 3 and Graphire 4. I assume this is why my tablet is not recognized? or is it supposed to use the graphire-usb.tablet, or even the generic.tablet?

If the tablet is indeed unsupported, is there a way to add it?

EDIT: as a test, I tried to create a graphire2.tablet in /usr/share/libwacom with the following and it seems to work, at least partly:

```
# Wacom
# Graphire 2
# ET-0405A-U
#
# Button Map:
# (A=1, B=2, C=3, ...)
#
#      *----------------------*
#      |                      |
#      |                      |
#      |                      |
#      |        TABLET        |
#      |                      |
#      |                      |
#      |                      |
#      *----------------------*
#

[Device]
Name=Wacom Graphire 2
DeviceMatch=usb:056a:0011
Class=Graphire
Width=5
Height=4

[Features]
Stylus=true
Buttons=0
```

The tablet is now seen in the Wacom Tablet tool, in the "Tablet" tab. But nothing is seen in the "Stylus" one, not sure it's normal (i.e. is it for newer/professional tablets that have advanced styluses or something?).

**Comment by jigpu** [comment] 2017-05-24 19:14
The "Stylus" tab should at least have a "General Pen" entry that allows configuration of your pen's side switches and the pressure curve. This is used as a fallback when no other pen is explicitly listed in the tablet definition file. Could you please run `libwacom-list-local-devices` and post its output? Afterward, please try adding the following line under the "[Device]" section: `Styli=0xfffff;0xffffe;` -- this explicitly tells libwacom that the tablet uses the fallback pen.

**Comment by terzag** [comment] 2017-05-24 19:31
I get this when running libwacom-list-local-devices:

```
[Device]
Name=Wacom Graphire 2
DeviceMatch=usb:056a:0011;
Class=Graphire
Width=5
Height=4
IntegratedIn=
Styli=0xfffff;0xffffe;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=0
```

Looks like it already uses the default Stylu value? In any case, I just added the line to my graphire2.tablet file and no change in the GNOME settings, still no stylus anywhere.

**Comment by jigpu** [comment] 2017-05-24 21:59
Indeed, it looks like libinput is providing the proper data, so the problem is likely higher up the stack. Oddly, however, the Graphire4 that I have handy has its "General Pen" stylus showing up just fine in GNOME 3.24 (Arch Linux). I'm not sure why one would work but not the other...

**Comment by terzag** [comment] 2017-05-24 22:50
I can try with Manjaro to check if it behaves differently.

**Comment by terzag** [comment] 2017-05-25 12:04
So, I installed Manjaro on a laptop I have, updated it to get GNOME 3.24, copied my .tablet file and I have the same behavior as on Ubuntu: tablet appear in the Tablet tab but nothing in the Stylus one.

In both cases, I haven't compiled libwacom from your repo, only added the .tablet file. Do I need to compile the lib?

**Comment by jigpu** [comment] 2017-05-25 20:57
In this case, no; adding the tablet file without recompiling should be fine. I wondered if it might have something to do with the pen being "newly discovered", but after creating a new user account on my machine my Graphire4 shows up fine in its control panel. I'm downloading a copy of Ubuntu GNOME and will try to see how it behaves.

**Comment by terzag** [comment] 2017-08-15 19:51
Have you been able to check Ubuntu GNOME?

**Comment by jigpu** [comment] 2018-01-04 22:22
Yes, this is more than likely an issue with the Wacom panel within the GNOME Control Center. I'd suggest filing a bug at https://bugzilla.gnome.org/ with the details.

A tablet definition for the two Graphire2 models will be included with the next release of libwacom.

**Closed by jigpu** 2018-01-04 22:22 UTC

**Comment by terzag** [comment] 2018-01-05 09:07
> A tablet definition for the two Graphire2 models will be included with the next release of libwacom.

Nice. :)

Just in case, here is the graphire1.tablet that I made for someone, it might be useful to add it too:

# Wacom
# Graphire
# ET-0405-U
#
# Button Map:
# (A=1, B=2, C=3, ...)
#
#      *----------------------*
#      |                      |
#      |                      |
#      |                      |
#      |        TABLET        |
#      |                      |
#      |                      |
#      |                      |
#      *----------------------*
#

[Device]
Name=Wacom Graphire
DeviceMatch=usb:056a:0010
Class=Graphire
Width=5
Height=4

[Features]
Stylus=true
Buttons=0

**Comment by jigpu** [comment] 2018-01-05 18:26
A data file for the original Graphire has already been added as of the libwacom-0.25 release :)

**Comment by terzag** [comment] 2018-01-05 18:52
Ok, cool. :)
