### ISSUE TITLE
Can't draw and zoom in X1 Yoga gen 3 (2018) 

### ISSUE THREAD

**Issue by hieu29791** [linuxwacom/libwacom#66] opened 2019-02-04 16:28 UTC
Hi, 
I have X1 Yoga Gen 3(2018) and install Manjaro KDE on it. I already install libwacom and xf86-input-wacom package, but pen can't draw, just have default function like finger. I read troubleshooting but don't know how to fix it.
Also I can't zoom in the touch screen by pinch in, pinch out. And touch screen seem like a little bit delay, inaccuracy for me(scrolling not smooth as touchpad).
Here is my command, if you want to know more information, let me know.
```
libwacom-list-local-devices
[Device]
Name=Wacom Serial Tablet WACf004
DeviceMatch=serial:0000:0000;
Class=ISDV4
Width=0
Height=0
IntegratedIn=Display;System;
Styli=0xfffff;0xffffe;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=0
```
Thank you!

**Comment by jigpu** [comment] 2019-02-04 22:01
Could you please run our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) and attach the generated tarball here? That should hopefully give us enough information to start tracking down the cause.

**Comment by hieu29791** [comment] 2019-02-04 23:36
> Could you please run our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) and attach the generated tarball here? That should hopefully give us enough information to start tracking down the cause.

I attached tar file as your request, thanks for your quick reply.
[sysinfo.rY7AXS73kG.tar.gz](https://github.com/linuxwacom/libwacom/files/2830196/sysinfo.rY7AXS73kG.tar.gz)

**Comment by hieu29791** [comment] 2019-02-08 09:45
After inspecting the problem, I realize when I type **_lsusb_** command, ID is **056a:5147**, but on your isdv4-5146.tablet file ID is **5146**, so **_libwacom-list-local-devices_** command will not show information of my laptop.
```
lsusb       
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0bda:0328 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 06cb:009a Synaptics, Inc. 
Bus 001 Device 003: ID 04f2:b61e Chicony Electronics Co., Ltd 
Bus 001 Device 002: ID 8087:0a2b Intel Corp. 
Bus 001 Device 005: ID 056a:5147 Wacom Co., Ltd 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
My pen, seem like it's ok. I can draw, open app, did the same thing as touchpad.  
But with my touchscreen, I can't execute action like open app, setting, panel, dock ... with single click/double click. On browser, I can't zoom with multi-touch like pinch in/out, and gesture on each browser is different. For example, scrolling with one finger on chrome and two finger on firefox. What I want is do the same thing as touchpad can do(everything), and plus other function of touchscreen like multi-touch(pinch).  
Thanks!

**Comment by jigpu** [comment] 2019-02-08 15:42
Can you run `echo $XDG_SESSION_TYPE` in a terminal and reply back with the result?

It looks like there's some kind of error that occurs shortly after startup which is causing the devices to disappear. The kernel clearly sees them, and they're detected by the desktop as well. A minute after the system started up though, this error was logged and the devices removed: `Error reading wacom device : No such device`. I don't see a corresponding error in the kernel log, however.

I would suggest downloading Ubuntu 18.04 onto a USB stick and temporarily booting into it to see if the pen and touchscreen behave differently / reliably. This should tell us if the problem is more likely to be a software issue in Majaro or a hardware issue that affects all distros.

The absence of a `isdv4-5147.tablet` file won't cause any trouble for the driver, but it will prevent the GNOME Control Center from allowing you to configure the pen. We'll want to create a new file, but some of the necessary device information is missing from the sysinfo output since the device disappeared. If the pen and touchscreen work reliably in Ubuntu 18.04, you should re-run sysinfo.sh from there and attach its output for comparison.

**Comment by hieu29791** [comment] 2019-02-11 13:33
> Can you run `echo $XDG_SESSION_TYPE` in a terminal and reply back with the result?
> 
> It looks like there's some kind of error that occurs shortly after startup which is causing the devices to disappear. The kernel clearly sees them, and they're detected by the desktop as well. A minute after the system started up though, this error was logged and the devices removed: `Error reading wacom device : No such device`. I don't see a corresponding error in the kernel log, however.
> 
> I would suggest downloading Ubuntu 18.04 onto a USB stick and temporarily booting into it to see if the pen and touchscreen behave differently / reliably. This should tell us if the problem is more likely to be a software issue in Majaro or a hardware issue that affects all distros.
> 
> The absence of a `isdv4-5147.tablet` file won't cause any trouble for the driver, but it will prevent the GNOME Control Center from allowing you to configure the pen. We'll want to create a new file, but some of the necessary device information is missing from the sysinfo output since the device disappeared. If the pen and touchscreen work reliably in Ubuntu 18.04, you should re-run sysinfo.sh from there and attach its output for comparison.

Thanks for your answer, after a few days find the solution. Finally, I found a solution for this, refer to this page: https://bugs.launchpad.net/ubuntu/+source/xf86-input-wacom/+bug/1774242. It's working after change driver from "Wacom" to "libinput". Chrome working perfectly but Firefox need to add "Exec=env MOZ_USE_XINPUT2=1 /usr/lib/firefox/firefox --private-window %u" to /usr/share/applications/firefox.desktop

The only problem right now is touch screen and pen don't work after suspend. lsusb command not show Wacom driver anymore, I need to reboot to active this again. I'm not find the solution yet.
```
lsusb       
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0bda:0328 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 06cb:009a Synaptics, Inc. 
Bus 001 Device 003: ID 04f2:b61e Chicony Electronics Co., Ltd 
Bus 001 Device 002: ID 8087:0a2b Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by taaem** [comment] 2019-05-20 15:52
@hieu29791 I'm assuming you're using the patched acpi tables for enabling deep sleep on the X1?
Lenovo just released an update with official S3 sleep support, in which the touchscreen does work after suspend!

**Comment by jigpu** [comment] 2019-07-17 22:03
@hieu29791 Would it be possible for you to re-run the sysinfo script now that the touchscreen is working on your system? It would still be nice to have your 056a:5147 device recognized by the GNOME Control Center.

**Comment by whot** [comment] 2021-07-16 00:18
needinfo and no updates for 2 years, closing

**Closed by whot** 2021-07-16 00:18 UTC
Labels: need info
