### ISSUE TITLE
Thinkpad Pen Pro is not recognized by libwacom

### ISSUE THREAD

**Issue by taaem** [linuxwacom/libwacom#57] opened 2018-12-03 07:21 UTC
**Device name**
Thinkpad Pen Pro on a Thinkpad X1 Yoga 3rd Gen (Wacom ISDv4 5146)

**Device model identifier**
SD60M68133 (only number I could find)

**udevadm info output**
➜  ~ udevadm info /sys/class/input/event7  
P: /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.1/0003:056A:5146.0002/input/input16/event7
N: input/event7
S: input/by-id/usb-Wacom_Co._Ltd._Pen_and_multitouch_sensor-if01-event-mouse
S: input/by-path/pci-0000:00:14.0-usb-0:10:1.1-event-mouse
E: DEVLINKS=/dev/input/by-id/usb-Wacom_Co._Ltd._Pen_and_multitouch_sensor-if01-event-mouse /dev/input/by-path/pci-0000:00:14.0-usb-0:10:1.1-event-mouse
E: DEVNAME=/dev/input/event7
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.1/0003:056A:5146.0002/input/input16/event7
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_HEIGHT_MM=174
E: ID_INPUT_TABLET=1
E: ID_INPUT_WIDTH_MM=309
E: ID_MODEL=Pen_and_multitouch_sensor
E: ID_MODEL_ENC=Pen\x20and\x20multitouch\x20sensor
E: ID_MODEL_ID=5146
E: ID_PATH=pci-0000:00:14.0-usb-0:10:1.1
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_10_1_1
E: ID_REVISION=0003
E: ID_SERIAL=Wacom_Co._Ltd._Pen_and_multitouch_sensor
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_VENDOR=Wacom_Co._Ltd.
E: ID_VENDOR_ENC=Wacom\x20Co.\x2cLtd.
E: ID_VENDOR_ID=056a
E: LIBINPUT_DEVICE_GROUP=3/56a/5146:usb-0000:00:14.0-10
E: LIBINPUT_FUZZ_00=4
E: LIBINPUT_FUZZ_01=4
E: MAJOR=13
E: MINOR=71
E: SUBSYSTEM=input
E: USEC_INITIALIZED=18289453

**Comment by whot** [comment] 2018-12-11 01:14
This should've been merged with 81ee1f5ce1fc2c8ddcbe3eb51444d6f859ee80ea back in April. What version of libwacom are you on?

**Comment by taaem** [comment] 2018-12-11 07:36
I'm using libwacom 0.32, I just tested with a different Lenovo pen (don't know the exact version) and that also isn't recognized. To be clear, my tablet is recognized and I can calibrate in Gnome Settings but only the pen never shows up even if I put directly on the display.

**Comment by whot** [comment] 2018-12-12 05:44
checking again, this tablet doesn't have a specific pen type, this is just the fallback pen. There's a known gnome issue with that filed here: https://bugzilla.gnome.org/show_bug.cgi?id=793499

I've reproduced this with gnome on xorg, it works fine with gnome on wayland.  I'm closing this for libwacom because afaict libwacom does everything correctly here.

**Comment by taaem** [comment] 2018-12-12 18:59
So I just tested and debugged a bit and my pen is recognized as 0x11, which is not the one that is used in the gnome bug. Also my Pen only has 1 button, because the second button actually acts as eraser, so I don't know if this one actually falls into "Generic Pen". If I add a definition for 0x11 everything shows up as expected under Xorg and Wayland.

**Comment by whot** [comment] 2018-12-14 02:07
Can you attach an evemu-record of a short pen stroke please? And under Xorg, please run xinput watch-props <the device name> and then bring the pen into proximity. Attach the full output here please.

the device name is listed in xinput list, pick the Pen device.

**Comment by taaem** [comment] 2018-12-14 05:32
Here are the logs. As you can see in the xinput log the device ID is 17 (0x11).
[evemu-record.txt](https://github.com/linuxwacom/libwacom/files/2678776/evemu-record.txt)
[xinput-watch-props.txt](https://github.com/linuxwacom/libwacom/files/2678777/xinput-watch-props.txt)

**Comment by whot** [comment] 2018-12-17 03:43
cc @jigpu, a stylus id 0x11 is a new one?

**Comment by jigpu** [comment] 2018-12-18 00:18
Let me look and see what kind of info I can find...

**Comment by taaem** [comment] 2019-01-30 07:16
Hello, are there any updates on this?

**Comment by jigpu** [comment] 2019-02-08 22:30
My apologies; I'll send another inquiry since I haven't heard anything yet.

**Comment by jigpu** [comment] 2019-02-13 23:21
Got a response back and it looks like different AES pens do indeed return different tool type values. If I'm understanding correctly, the 0x11 pen is a Lenovo "mini pro" pen with no Bluetooth button(?) and which is rechargeable. Does that sound about right @taaem?

There's a whole list of different pens... This could be fun @whot :|

**Comment by whot** [comment] 2019-02-13 23:41
Thinking out aloud: 
Would it make sense to merge the styli into sets of known devices that we can assign to the tablets? Something like 
```
StyliSets=intuos-styli;intuos-puck
```
to help with updating when new styli come out. This would be step one. Step two is a stylus definition that can take an ID range, e.g.

```
[AES Pens]
IDs=0x11;0x12;0x14-0x18
AddToSet=AES
...
```

And then the various compatible devices get the `AES` set assigned. Still requires lots up updating, but long-term it's a bit easier to maintain, I think.

**Comment by taaem** [comment] 2019-02-14 07:05
@jigpu yes that sounds like the pen I have, it's a really basic pen.

**Comment by taaem** [comment] 2019-04-24 07:08
Are there any updates on this?

**Comment by jigpu** [comment] 2019-04-24 14:27
Unfortunately, I don't think either of us has had time to work on this particular issue yet.

As a workaround, you could try adding the following line to the "[Device]" section of `/usr/share/libwacom/isdv4-5146.tablet` and then rebooting: `Styli=0x11` That should help the situation, though the GNOME bug mentioned above still might(?) be a problem unless you're using GNOME 3.32.

**Comment by DSchndr** [comment] 2019-06-23 18:44
The workaround also works with the thinkpad active pen (sd60g97200, id: 0x21).

Thanks! :)

**Comment by jigpu** [comment] 2019-07-16 17:32
Reports of another missing ID: https://github.com/linuxwacom/libwacom/pull/128#issuecomment-511636991

**Comment by johrpan** [comment] 2020-01-29 19:22
I have the same stylus and the workaround works. Just out of interest: What is the reason for not adding the stylus definition here?

**Comment by whot** [comment] 2020-01-31 03:59
Maintainability - you'd need to update every `.tablet` file for compatible tablets for every stylus id. With the grouped approach (which is now merged btw) you only need to update one file. The `aes` group is still missing but the groundwork has been put in place.

**Comment by whot** [comment] 2022-08-03 03:11
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks

**Closed by whot** 2022-08-03 03:11 UTC
