### ISSUE TITLE
Lenovo Miix 520-IKB - Touch works, Pen not detected in Manjaro GNOME 

### ISSUE THREAD

**Issue by malcolmturnbull** [linuxwacom/libwacom#321] opened 2020-12-30 02:38 UTC
Hi, 
I have been trying to get the stylus for my tablet (Lenovo Miix 520-IKB) to work on a fresh install of Manjaro GNOME - I had this working in the past, but now it does not appear that the stylus or its button inputs are used at all. I am trying to wrap my head around whether this is Wayland related or my config but thought it could be helpful to provide the output of libwacom-list-local-devices. Thanks. 

```
~ >>> >....                                                                     
Name=Wacom ISDv4 513B
ModelName=
DeviceMatch=i2c:056a:513b;
Class=ISDV4
Width=10
Height=6
IntegratedIn=Display;System;
Styli=0x1;0x11;0x19;0x21;0x31;0x39;0x49;0x71;0x221;0x231;0x271;0x421;0x431;0x621;0x631;0x8051;0x805b;0x806b;0x807b;0x826b;0x846b;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=true
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=0
```

**Comment by malcolmturnbull** [comment] 2020-12-30 02:49
brief update that the pen and touch screen do not appear to see any inputs when using GNOME on XOrg option on log-in. xinput --list returns: 
~ >>> xinput --list                                                            
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SIPODEV Lenovo HID Device Mouse         	id=10	[slave  pointer  (2)]
⎜   ↳ SIPODEV Lenovo HID Device Touchpad      	id=12	[slave  pointer  (2)]
⎜   ↳ WCOM513B:00 056A:513B stylus            	id=14	[slave  pointer  (2)]
⎜   ↳ WCOM513B:00 056A:513B touch             	id=15	[slave  pointer  (2)]
⎜   ↳ WCOM513B:00 056A:513B Mouse             	id=16	[slave  pointer  (2)]
⎜   ↳ WCOM513B:00 056A:513B Touchscreen pad   	id=17	[slave  pointer  (2)]
⎜   ↳ WCOM513B:00 056A:513B eraser            	id=21	[slave  pointer  (2)]
⎜   ↳ WCOM513B:00 056A:513B pad               	id=22	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ SIPODEV Lenovo HID Device               	id=9	[slave  keyboard (3)]
    ↳ SIPODEV Lenovo HID Device Consumer Control	id=11	[slave  keyboard (3)]
    ↳ SIPODEV Lenovo HID Device Wireless Radio Control	id=13	[slave  keyboard (3)]
    ↳ Intel Virtual Button driver             	id=18	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=19	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=20	[slave  keyboard (3)]

**Comment by whot** [comment] 2021-01-04 04:35
Note that libwacom doesn't have an affect on how the tablet works, merely how it shows in GNOME. even `libwacom-list-local-devices` only looks up the vid/pid of every device in the system and then checks if there is a data file matching that vid/pid. So all it verifies here is that the device is present in the system and that libwacom has a data file for it.

if `xsetwacom` lists the devices this means they're recognised and added by the wacom driver. That effectively limits the issue to either the device/kernel or the wacom driver/X. Easiest to test is by running `libinput record` against the device and checking if any events are produced when you use the stylus or press the buttons. If not, then the issue is definitely in the device itself or the kernel.

If there are events, please attach the `libinput record` output so we can take a look and guess why it's not handled correctly. Please do also check your journal file for any errors from X.

**Comment by whot** [comment] 2022-06-28 05:38
This looks to be a gnome issue, from over a year ago, let's close it.

**Closed by whot** 2022-06-28 05:38 UTC
