### ISSUE TITLE
Yoga 9i 5201 <-- need a hint for the device match 

### ISSUE THREAD

**Issue by JacksonSarah** [linuxwacom/libwacom#523] opened 2022-09-11 10:22 UTC
#my Sysinfo: https://github.com/linuxwacom/wacom-hid-descriptors/issues/258 
#Lenovo Yoga 9i 15 IMH0515     [ Wacom HID 5201]
#What is working right now: The pen gets detected, from the device itself, some basic touch, pen gets detected by the energy #monitoring Sytem
#What is not working: Touch gestures, (Scrolling, Pinching etc…), and the gnome wacom setup tool tells me there is no pen #detected.
#Strange part: It worked on the Linux mint Live Stick, but not after the installation of the system and the big update. 
#So I thought I am going to write a new  .tablet file,  because the script [git-update.sh](https://github.com/linuxwacom/wacom-hid-descriptors/blob/master/scripts/git-update.sh), is not able to do it.

#What is my plan:
#My plan is to set up a config where you are able, not only to adjust the inbuild pen. 
#Because it seems that, the device itself is able to recognize tilt. But the Lenovo integrated Pen just support pressure sensitivity.
#So it would be nice to be able to set up also a Precision Pen 2 or other AES 2 Styli, with a tilt option
#As far as I know so far Linux is able to recognice the two different pens I have but, Im not sure how to tell the System that 
#there are two different Styli. The Linux driver seems to be more built in chip orientated. 
#So my cheat Idea was a config with an implented, tilt option.

#What is already finished  

[Device]
Name= Wacom HID 5201 Pen; Wacom HID 5201 Finger, Wacom HID5201 Touch
ModelName=
DeviceMatch=i2c:056a:5201
IntegratedIn=Display;System

[Features]
Stylus=true
Reversible=true
Touch=true
Buttons=2
Top=A
Bottom=B
Axis=tilt;pressure

#Where I need help:
#After copying the  .tablet in the  /usr/share/libwacom directory 
#I got that output:
#user@user:~/Dokumente$ libwacom-list-local-devices
#Missing DeviceMatch= line in '/usr/share/libwacom/WacomHID5201.tablet'

#(libwacom-list-local-devices:19096): GLib-CRITICAL **: 12:05:19.681: g_array_free: assertion 'array' failed

#(libwacom-list-local-devices:19096): GLib-CRITICAL **: 12:05:19.681: g_array_free: assertion 'array' failed
#/dev/input/event6 is a tablet but not supported by libwacom
#Failed to find any devices known to libwacom.

#So probably my Device Match is wrong and I have some trouble with the Class and the Styli= part to.
#I would be glad, if someone would take the time and give me a hand, with editing the missing parts or explaining me how to #to do it. I am using Linux for quite some time now, but never
#did advanced stuff like this, so please give a noob compatible explanation. Also, feel free to correct every mistake in the .tablet #I worked out so far.
#Greetings :)

**Comment by JacksonSarah** [comment] 2022-09-12 09:05
Did a bit more research, I had a Kubuntu 22.04 tested once. 
So there is my pen somehow recogniced. As I found out my device is already listed in the https://github.com/KDE/wacomtablet.
But there ain´t no chancefor porting from there, becouse there own .tablet Data gets read out without a device match.

It is becoming more weird, because if I check my Laptop with hardinfo, a gui driven and more noob compatible program, every listed input device has that little code thing I need for the device match. Exept the Wacom devices. The only output I was able to get was
Name Wacom HID 5201 (Finger,Pen, etc)
Type Mouse
Bus 0x18 
Manufacturer 0x56a
Product 0x5201
Version 0x100
Connected to i2c-WAC212A:00

So there are two questions left about that, 
is the whole problematic, comes from the fact that my laptop tells the system my touchdevice is a mouse?
Any chance for a work around?

**Comment by JacksonSarah** [comment] 2022-09-25 14:15
So after a lot of research my pen, is detected by my settings program but.
I still have a lot of trouble with the fine-tuning.
- Touch gestures are still not really implemented, but I guess it's more a cinnamon driven problem.
- Button mapping:
 Linux Mint still thinks I just have one button in every pen, and I am clueless, how to convince my software to recognize both of    
 them.
-Gordic Brain not: 
 Linux is aware of, the existence of the to different pens I am working with. The inbuilt garage pen and the precision pen 2. 
 What exactly must I do to be map both of them properly? 
 I have, the main device touchscreen with sensor and three inputs, finger and two different pens. 
 Do I have to put the second pen in the .tablet file of my main device and add it as an extra pencil, or do I have to add it in a special aes pen collection .tablet
-tilt: Works fine at Krita, but It's still not recognized by my settings program.

I would be thankfull for any kind of hints

**Comment by whot** [comment] 2022-11-17 01:12
a few comments:
- git-update.sh is a script for maintainers, you need to run `sysinfo.sh` instead
- libwacom has no effect on whether the tablet works. It's merely a static database of device info we can't get from the kernel device (model name, is it integrated?, etc.)
- libwacom now supports `/etc/libwacom` as well so you can copy your .tablet file there instead of having to mess with the system files
- you probably need `Styli=@isdv4-aes` or somesuch to specify which styli are supported
- `libwacom-list-local-devices` should list your device once the tablet file is installed. if that works, the libwacom bits are complete
- `libinput debug-events` is easiest to test for functionality, whatever that doesn't show won't show up well in the upper layers of the stack either. even where you use xf86-input-wacom under X, it's likely the same issues will be seen

**Comment by whot** [comment] 2023-01-12 23:45
>  and a eraser setting for a pen wich doesn't have one

unfortunately (virtually?) all AES pens have that button hard-coded to be an eraser button. To the point that the pen actually pretends to go out of proximity and back into proximity as eraser in the HID protocol (i.e. the protocol the tablet itself sends). This has been the case for... [a long time now](https://who-t.blogspot.com/2014/09/stylus-behaviour-on-microsoft-surface-3.html).

We've looked at trying to make it possible to map that to be a real button in the driver (xf86-input-wacom and libinput), but the heuristics required are nontrivial and it's unlikely to ever happen.

So, it's an inconvenience but not a bug, or at least not our fault  :smile:

**Comment by JacksonSarah** [comment] 2023-01-13 10:44
Thanks for your fast reply, 
It's good to know that it's not a problem solvable by a DIY person which, just tweaks some config files. 
Also, it is a bit sad, because of this fact it seems unlikely that I will be able to fully use my precious hardware and I wished I've known before, a second button just would make Krita more usable with 2 in 1 devices. 
So maybe it's time to clean my tablet file and load it up

**Comment by whot** [comment] 2023-11-27 00:24
Closing this one, looks like right now the only thing missing is to get the `.tablet` file merged and let's do that via a PR please, thanks.

**Closed by whot** 2023-11-27 00:24 UTC
