### ISSUE TITLE
ACER SPIN 5 (SP513-54N) stylus Wacom HID 495F Pen not recognized 

### ISSUE THREAD

**Issue by crysman** [linuxwacom/libwacom#278] opened 2020-07-11 15:21 UTC
I've already tried adding this
```
#crysman has added experimental ACER SPIN5
#(0x11 hex = 17 dec), id taken by first line of `sudo libinput record | grep -i abs_misc`
[0x11]
Name=Wacom HID 495F Pen
Buttons=2
HasEraser=false
Axes=Pressure;Distance;
Type=General
```
to `/usr/share/libwacom/libwacom.stylus` but not working :(

Here is requested debug info:

**Device name**

> Wacom HID 495F

**Device model identifier**

> xsetwacom --list
Wacom HID 495F Pen stylus id: 9 type: STYLUS
Wacom HID 495F Finger touch id: 10 type: TOUCH
Wacom HID 495F Pen eraser id: 18 type: ERASER

 
**udevadm info output**
```
user@SPIN5:~$ sudo libinput record | grep -i abs_misc
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Sleep Button
/dev/input/event2:	AT Translated Set 2 keyboard
/dev/input/event3:	Microsoft Microsoft 3-Button Mouse with IntelliEye(TM)
/dev/input/event4:	Wacom HID 495F Pen
/dev/input/event5:	Wacom HID 495F Finger
/dev/input/event6:	PS/2 Logitech Wheel Mouse
/dev/input/event7:	Intel HID events
/dev/input/event8:	Acer WMI hotkeys
/dev/input/event9:	Video Bus
/dev/input/event10:	Intel HID 5 button array
/dev/input/event12:	ELAN0515:00 04F3:3142 Mouse
/dev/input/event13:	ELAN0515:00 04F3:3142 Touchpad
/dev/input/event14:	sof-hda-dsp Headphone
/dev/input/event15:	sof-hda-dsp HDMI/DP,pcm=3
/dev/input/event16:	sof-hda-dsp HDMI/DP,pcm=4
/dev/input/event17:	sof-hda-dsp HDMI/DP,pcm=5
Select the device event number: 4
Recording to 'stdout'.
    #   Event code 40 (ABS_MISC)
    - [  0,      0,   3,  40,      17] # EV_ABS / ABS_MISC                 17 (+17)
    - [  0, 245251,   3,  40,       0] # EV_ABS / ABS_MISC                  0 (-17)
^C
user@SPIN5:~$ udevadm info /sys/class/input/event4
P: /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-CUST0000:00/0018:056A:495F.0001/input/input14/event4
N: input/event4
L: 0
S: input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-CUST0000:00/0018:056A:495F.0001/input/input14/event4
E: DEVNAME=/dev/input/event4
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: USEC_INITIALIZED=4525449
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_INPUT_WIDTH_MM=284
E: ID_INPUT_HEIGHT_MM=189
E: ID_SERIAL=noserial
E: ID_PATH=pci-0000:00:15.0-platform-i2c_designware.0
E: ID_PATH_TAG=pci-0000_00_15_0-platform-i2c_designware_0
E: LIBINPUT_DEVICE_GROUP=18/56a/495f:i2c-CUST0000:00
E: DEVLINKS=/dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse
```

Please take into consideration I am currently running Ubuntu with these kernel cmd options: `i8042.nopnp=1 pci=nocrs`  because of this bug: https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1884746

Thanks for help!

**Comment by jigpu** [comment] 2020-07-13 16:17
Can you please describe what exactly isn't working / recognized? What behavior are you expecting, and what is actually happening?

**Comment by crysman** [comment] 2020-07-13 20:57
@jigpu I'll try my best:

1. the main issue is that although pen/stylus is working, it is **basically just moving the mouse cursor**. When I touch the screen with the pen and move up/down to scroll, it does not scroll. On the contrary when I do it with bare finger - it behaves properly - scrolls. This is expected behavior as known from MS Windows.

1. second, in `Settings -> Wacom Tablet` (standard latest Ubuntu GNOME ("focal")) it states "_No stylus found Please move your stylus to the proximity of the tablet to configure it_" : 
![image](https://user-images.githubusercontent.com/5269350/87352577-91617300-c55b-11ea-8f79-788b5bdf26c8.png) - I hope it will allow me, once there, to set holding stylus "pinned" in the screen to emulate secondary mouse button etc.

Hope this helps enough to describe the issue.. ? Thanks!

**Comment by crysman** [comment] 2020-07-18 10:40
Anything I can do here to help?

**Comment by jigpu** [comment] 2020-07-21 15:40
Apologies for the delay.

> the main issue is that although pen/stylus is working, it is basically just moving the mouse cursor. When I touch the screen with the pen and move up/down to scroll, it does not scroll. On the contrary when I do it with bare finger - it behaves properly - scrolls. This is expected behavior as known from MS Windows.

This is normal behavior for Linux. Most applications treat the pen like a mouse, not a finger, so dragging up and down with it has the same effect as dragging up and down with the mouse. You may want to file a new issue at https://gitlab.gnome.org/GNOME/gtk/-/issues to request the feature for applications built on GTK.

The xf86-input-wacom driver itself can emulate the behavior if you use `xsetwacom set <stylus> button <n> pan` with either button 2 or 3. It isn't exactly the same, however. You have to hold the programmed button down while dragging with this method (instead of just dragging), and the scrolling is "chunky" rather than smooth since the driver is just sending mousewheel events under the hood.

> second, in Settings -> Wacom Tablet (standard latest Ubuntu GNOME ("focal")) it states "No stylus found Please move your stylus to the proximity of the tablet to configure it". I hope it will allow me, once there, to set holding stylus "pinned" in the screen to emulate secondary mouse button etc.

If the pen settings do not appear, that indicates that the control panel does not recognize your pen. The usual culprit is an out-of-date libwacom database. It looks like your particular sensor (495F) isn't in the database either. Can you run our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) to gather the info necessary to generate a new database entry and then attach it to a new [wacom-hid-descriptors bug report](https://github.com/linuxwacom/wacom-hid-descriptors/issues)? From there I can update libwacom and help you install the updated version.

**Comment by crysman** [comment] 2020-07-23 20:09
I've created the issue: https://github.com/linuxwacom/wacom-hid-descriptors/issues/98 thanks

**Comment by jigpu** [comment] 2020-07-24 15:33
I've created a libwacom tablet definition for your sensor based on the sysinfo you've provided. To have your _sensor_ show up in the GNOME Control Center (the "Tablet" button at the top of the window in your screenshot above), it should be sufficient to just save the file into the `/usr/share/libwacom` directory.

Getting your stylus to show up is a little more work: you'll need to build libwacom from source. I'm going to temporarily hold off on instructions for that until libwacom has merged the request so that there's a little less hoop jumping necessary.

**Comment by crysman** [comment] 2020-07-25 05:15
confirming "tablet" tab active now after copying new tablet definition into /usr/share/libwacom:
![image](https://user-images.githubusercontent.com/5269350/88449351-6eca3680-ce46-11ea-92ad-22048583960f.png)

ad stylus/pen:
OK, awaiting further info. I'll gladly test it building from source - for the others to have it "shipped for free" in next Ubuntu release ;)

**Comment by crysman** [comment] 2020-08-12 19:24
@jigpu hello, I just want to know if there is any progress here (?) - something to test?

**Comment by whot** [comment] 2022-08-03 03:13
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks

**Closed by whot** 2022-08-03 03:13 UTC
