### ISSUE TITLE
Problems with Wacom Bamboo stylus

### ISSUE THREAD

**Issue by alleyjack** [linuxwacom/libwacom#43] opened 2018-09-13 20:18 UTC
Just updated my PC from the last LTS Ubuntu distro to 18.04LTS, and the stylus on my Wacom Wireless Bamboo tablet immediately lost all button function.

The system seems to be tracking the stylus itself, as moving it over the pad causes the cursor to move around the screen, but touching the stylus to the pad and/or clicking the button on the stylus body gets no response.

The touchpad function on the tablet itself, on the other hand, responds to finger drags and taps as cursor movement and clicks, respectively. The A/B buttons at the foot of the tablet do not respond, same as the stylus buttons. Deets as follows:

**Tablet Model:** Wacom Bamboo Pad (Wireless), CTH-300/K  
**System:** Ubuntu 18.04.1 LTS, 64-bit

**Devices > Wacom Tablet:** Displays "No stylus found / Please move your stylus to the proximity of the tablet to configure it" and doesn't respond to stylus cursor movement in that area. `Tablet > Wacom Bamboo Pad Wireless > Tracking Mode` is "Tablet (absolute)". Trying to use "Map Buttons..." to set the A/B tablet buttons doesn't work; they display on screen for mapping but don't respond to being pressed.

**libwacom-list-local-devices:**  
*One point I noticed:* Libwacom lists the tablet stylus as `0xfffff;0xffffe`, which are the codes for a default standard stylus and a stylus with an eraser. The stylus for the Bamboo Pad doesn't have an eraser or a rocker button, and should be set as type `0xffffd`. Not sure if this means it's related to [this bug][1] or not.

    [Device]
    Name=Wacom Bamboo Pad Wireless
    DeviceMatch=usb:056a:0319;
    Class=Bamboo
    Width=4
    Height=3
    IntegratedIn=
    Layout=bamboo-pad.svg
    Styli=0xfffff;0xffffe;
    
    [Features]
    Reversible=false
    Stylus=true
    Ring=false
    Ring2=false
    Touch=true
    TouchSwitch=false
    StatusLEDs=
    NumStrips=0
    Buttons=2
    [Buttons]
    Left=
    Right=
    Top=
    Bottom=A;B;
    Touchstrip=
    Touchstrip2=
    OLEDs=
    Ring=
    Ring2=
    EvdevCodes=0x110;0x111;
    RingNumModes=0
    Ring2NumModes=0
    StripsNumModes=0
    
    ---------------------------------------------------------------
    [Device]
    Name=Wacom Bamboo Pad Wireless
    DeviceMatch=usb:056a:0319;
    Class=Bamboo
    Width=4
    Height=3
    IntegratedIn=
    Layout=bamboo-pad.svg
    Styli=0xfffff;0xffffe;
    
    [Features]
    Reversible=false
    Stylus=true
    Ring=false
    Ring2=false
    Touch=true
    TouchSwitch=false
    StatusLEDs=
    NumStrips=0
    Buttons=2
    [Buttons]
    Left=
    Right=
    Top=
    Bottom=A;B;
    Touchstrip=
    Touchstrip2=
    OLEDs=
    Ring=
    Ring2=
    EvdevCodes=0x110;0x111;
    RingNumModes=0
    Ring2NumModes=0
    StripsNumModes=0
    
    ---------------------------------------------------------------

**xinput --list:**  
*Also lists an eraser that isn't there*

    ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
    ⎜   ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0	id=9	[slave  pointer  (2)]
    ⎜   ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0	id=10	[slave  pointer  (2)]
    ⎜   ↳ Wacom Wireless Bamboo PAD Pen stylus    	id=11	[slave  pointer  (2)]
    ⎜   ↳ Wacom Wireless Bamboo PAD Finger touch  	id=15	[slave  pointer  (2)]
    ⎜   ↳ Wacom Wireless Bamboo PAD Pen eraser    	id=12	[slave  pointer  (2)]
    ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
        ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
        ↳ Power Button                            	id=6	[slave  keyboard (3)]
        ↳ Power Button                            	id=7	[slave  keyboard (3)]
        ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0	id=8	[slave  keyboard (3)]
        ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0	id=13	[slave  keyboard (3)]
        ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0	id=14	[slave  keyboard (3)]

**xinput props:**  
*Noted that there are far more buttons listed than the stylus actually has.*

        /usr/share/libwacom$ xinput --list-props "Wacom Wireless Bamboo PAD Pen stylus"
    Device 'Wacom Wireless Bamboo PAD Pen stylus':
    	Device Enabled (139):	1
    	Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
    	Device Accel Profile (270):	0
    	Device Accel Constant Deceleration (271):	1.000000
    	Device Accel Adaptive Deceleration (272):	1.000000
    	Device Accel Velocity Scaling (273):	10.000000
    	Device Node (262):	"/dev/input/event5"
    	Wacom Tablet Area (299):	0, 0, 10690, 6680
    	Wacom Rotation (300):	0
    	Wacom Pressurecurve (301):	0, 0, 100, 100
    	Wacom Serial IDs (302):	793, 1, 2, 0, 0
    	Wacom Serial ID binding (303):	0
    	Wacom Pressure Threshold (304):	26
    	Wacom Sample and Suppress (305):	2, 4
    	Wacom Enable Touch (306):	1
    	Wacom Hover Click (307):	1
    	Wacom Enable Touch Gesture (308):	0
    	Wacom Touch Gesture Parameters (309):	0, 0, 250
    	Wacom Tool Type (310):	"STYLUS" (292)
    	Wacom Button Actions (311):	"Wacom button action 0" (312), "Wacom button action 1" (313), "Wacom button action 2" (314), "None" (0), "None" (0), "None" (0), "None" (0), "Wacom button action 3" (315)
    	Wacom button action 0 (312):	1572865
    	Wacom button action 1 (313):	1572866
    	Wacom button action 2 (314):	1572867
    	Wacom button action 3 (315):	1572872
    	Wacom Pressure Recalibration (316):	1
    	Wacom Panscroll Threshold (317):	1209
    	Device Product ID (263):	1386, 793
    	Wacom Debug Levels (318):	0, 0

**xinput test "Wacom Wireless Bamboo PAD Pen stylus":**

*Pen movement:*  

    motion a[0]=7676 a[1]=3667 a[2]=0 a[3]=0 a[4]=0 a[5]=-900 
    motion a[0]=7663 a[1]=3660 a[2]=0 a[3]=0 a[4]=0 a[5]=-900 
    motion a[0]=7656 a[1]=3650 a[2]=0 a[3]=0 a[4]=0 a[5]=-900 
    motion a[0]=7657 a[1]=3642 a[2]=0 a[3]=0 a[4]=0 a[5]=-900 
    motion a[0]=7669 a[1]=3637 a[2]=0 a[3]=0 a[4]=0 a[5]=-900 
    motion a[0]=7688 a[1]=3635 a[2]=0 a[3]=0 a[4]=0 a[5]=-900 
    (etc.)

*Pen "click"/touch:*  

    motion a[0]=7658 a[1]=3641 a[2]=31164 a[3]=0 a[4]=0 a[5]=-900 

*Pen button click:* No noticeable response

-----------------

If anyone has any ideas on how to proceed, I'd appreciate it. I'd like to try to remove the extra button mapping, reassign libwacom's styli code for the tablet, and/or find out exactly what the button action codes correspond to, but I'm having difficulty finding information on how to do any of that. (And I'd rather not kill what little functionality I still have.)

I've also had [issues with assigning persistent settings to this tablet in the past][2], though I'm not sure if that has anything to do with what's going on now.

  [1]: https://bugzilla.gnome.org/show_bug.cgi?id=793499
  [2]: https://superuser.com/questions/684303/wacom-on-ubuntu-how-to-make-button-associations-persistent/1115507#1115507

**Comment by jigpu** [comment] 2018-09-14 21:36
I believe this is a duplicate of https://github.com/linuxwacom/input-wacom/issues/40. The patch in that thread should work around the issue with the stylus not doing anything when it touches the tablet surface. An issue with the A/B button issue wasn't mentioned in that thread, so do let me know if the patch fixes that as well...

**Devices > Wacom Tablet:** The issue of the stylus not being detected in the control panel is almost certainly the [GNOME bug](https://bugzilla.gnome.org/show_bug.cgi?id=793499) that you linked to. It may be good to reply to that issue to let the GNOME developers that others are affected.

**libwacom-list-local-devices:**
**xinput --list:**
The use of `0xfffff;0xffffe;` and the appearance of the eraser device is correct since although the tablet's stock pen does not have an eraser, the tablet hardware itself claims to support erasing (if you can find a compatible pen from another model).

**xinput props:** Buttons 1-3 are normal (like the eraser support, the hardware describes 3 stylus buttons and could possibly report events if you found a compatible pen). Buttons 4-7 are "filler" buttons that get generated for compatibility reasons whenever more than three buttons are available -- this is expected given that button 8 exists. The existence of button 8 is arguably a bug since the hardware doesn't really support a fourth button, but is really just lazy programming (the driver just allocates/initializes the maximum number of buttons possible on a stylus, which at this moment is 4). The extra button doesn't cause problems since even the most inquisitive of programs would just treat it like a button that is never pressed.

**Comment by alleyjack** [comment] 2018-09-21 21:56
The patch worked for restoring stylus/tablet surface action, thank you! Unfortunately, the stylus body button and the tablet's A/B buttons still aren't working. The stylus body button is the next big one as I typically rely on it to serve as my "right click" functionality.

Running `xinput test` again, this time I get a response when clicking the stylus body button:

    button press   2 a[0]=6326 a[1]=4094 a[2]=0 a[3]=0 a[4]=0 a[5]=-900
    button release 2 a[0]=6390 a[1]=4062 a[2]=0 a[3]=0 a[4]=0 a[5]=-900

Touching the stylus to the tablet currently generates:

    button press   1 a[0]=6273 a[1]=4219 a[2]=19750 a[3]=0 a[4]=0 a[5]=-900
    button release 1 a[0]=6261 a[1]=4222 a[2]=0 a[3]=0 a[4]=0 a[5]=-900

Any insight? Do I just need to reassign button 2?

**Comment by alleyjack** [comment] 2018-09-24 16:45
Adding that on a reboot a middle swath of the tablet suddenly stopped responding to both stylus touch and finger touch on the touchpad. A reboot fixed it; if it happens again I'll try to grab some specs.

**Comment by jigpu** [comment] 2018-09-26 09:37
You might just need to reassign the button if you want the body button to perform a right click. It seems to be sending a middle-click (button 2) right now, so to remap it you could run `xsetwacom set <id> button 2 3`. If that works, I should be able to come up with an xorg.conf.d snippet which will apply that configuration preference automatically.

**Comment by alleyjack** [comment] 2018-09-26 16:55
Yep, that worked fine. Thanks!

**Closed** 2018-09-28 21:10 UTC

**Comment by boxbotteries** [comment] 2018-10-03 17:48
Hm, as a footnote, ran into an issue where a system update included some libwacom changes and I had to reapply the patch and reboot all over again. Any chance of the underlying issue there getting fixed so that doesn't have to be done every time?

**Comment by whot** [comment] 2018-10-04 04:18
Please see https://github.com/linuxwacom/input-wacom/issues/40, this is not something we can fix in libwacom as the issue is in mutter (and, less arguably, in the kernel drivers)
