### ISSUE TITLE
Add Dell XPS 15 9575

### ISSUE THREAD

**Issue by jigpu** [linuxwacom/libwacom#35] opened 2018-09-04 17:42 UTC
Sysinfo at https://github.com/linuxwacom/wacom-hid-descriptors/issues/37

**Comment by Element-126** [comment] 2018-09-18 21:27
As mentioned in the original issue, #39 makes the tablet visible in Gnome Control Center, but not the stylus. This makes it impossible to configure the buttons, rendering two of them useless.

By googling this issue, I found another user who seemed to have a similar problem:
https://askubuntu.com/questions/908756/how-do-i-configure-a-wacom-stylus-on-ubuntu-17-04
(Have a look at his answer as well: https://askubuntu.com/a/1067300)

What striked me is that he mentions that his stylus behaves either as a pen or an eraser depending on whether he presses the eraser button, and they are seen as two *separate* devices by xinput.
This seems to be the case on my system as well, although there is only one physical pen with no eraser tip:
```
$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Wacom HID 486A Pen stylus               	id=12	[slave  pointer  (2)]
⎜   ↳ Wacom HID 486A Finger touch             	id=13	[slave  pointer  (2)]
⎜   ↳ DELL080D:00 06CB:7A13 Touchpad          	id=14	[slave  pointer  (2)]
⎜   ↳ Wacom HID 486A Pen eraser               	id=20	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=10	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=11	[slave  keyboard (3)]
    ↳ Intel Virtual Button driver             	id=15	[slave  keyboard (3)]
    ↳ Intel HID events                        	id=16	[slave  keyboard (3)]
    ↳ Intel HID 5 button array                	id=17	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=18	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=19	[slave  keyboard (3)]
    ↳ Dell Active Pen PN579X Keyboard         	id=21	[slave  keyboard (3)]
```

I don't know whether this behavior is expected, or which component causes the issue.
libinput sees only one device, and is able to detect all button events, but the eraser mode seems to be hardwired and only one button is actually seen as a button. Could this be caused by a bad driver for this device ? Otherwise, should we need to adapt the *stylus* definition, instead of using the generic one?

This does not seem to be an isolated issue anymore, so let me know if there is anything I can do to help you tackle it!

To get you started, here is a simultaneous libinput event record and "debug-event" log:
* [buttons-debug-events.log](https://github.com/linuxwacom/libwacom/files/2394521/buttons-debug-events.log)
* [buttons-record.zip](https://github.com/linuxwacom/libwacom/files/2394523/buttons-record.zip) (zipped to make GitHub happy)

During this recording, it did the following:
1. Bring the pen in proximity, apply some pressure, then pull the pen out of proximity.
2. Repeat step 1 while maintaining the lower button pressed.
3. Repeat step 1 while maintaining the upper button pressed.
4. Bring the pen in proximity.
5. Press the lower button.
6. Press the upper button.
7. Pull the pen out of proximity.

*NB: In addition, the top button is seen as a separate (bluetooth) keyboard, but this seems unrelated to the issue at hand.*

**Comment by whot** [comment] 2018-09-19 00:07
> What striked me is that he mentions that his stylus behaves either as a pen or an eraser depending on whether he presses the eraser button, and they are seen as two separate devices by xinput.

That is fairly standard for many devices (MS ones, for example) and the expected behaviour for the xf86-input-wacom driver. The libinput driver should create the X devices as the stylus comes into proximity the first time.

> the eraser mode seems to be hardwired and only one button is actually seen as a button.

yep. see https://who-t.blogspot.com/2014/09/stylus-behaviour-on-microsoft-surface-3.html

This doesn't seem to be a libwacom bug anymore now, this is now https://bugzilla.gnome.org/show_bug.cgi?id=793499, right?

**Comment by Element-126** [comment] 2018-09-19 08:34
Thanks for the clarification! I guess this is what all pens advertising Windows Ink capabilities are going to do now... Because Microsoft obviously knows better than Wacom how to do tablets ;-)

BTW, could it be an issue that the pen has only one actual button, which does not match the generic stylus definition `0xfffff` ? (which has two buttons)

Otherwise, I guess you can close this issue since the tablet is recognized as expected.

I added myself to the CC list for the bug you mentioned.

**Comment by whot** [comment] 2018-10-09 05:38
no, whether there's one or two buttons doesn't really matter, no client that I know of really cares about that bit. I think this is just the ID mismatch here and needs to be fixed in the control center.

**Closed by whot** 2018-10-09 05:38 UTC
