### ISSUE TITLE
Support for Huion HS611

### ISSUE THREAD

**Issue by VoltageAmperage** [linuxwacom/libwacom#361] opened 2021-03-09 10:56 UTC
Hi!                                                                             
                                                                             
I've been trying to work on a tablet config file and svg for the Huion HS611 tablet. It shares the same usb identifier as the Huion h950p, so I used that as a starting place. I believe I have the EvdevCodes correct for the buttons, but I'm having difficulty with two things:
                                                                              
1. I am struggling to determine how to describe the touch strip. When I use evtest, the touch strip is divided into what seems like 4 buttons from left to right: BTN_8, BTN_9, BTN_SOUTH, and BTN_EAST. I can tap in these four segments and get the different button codes. How do I describe this in the tablet file?
2. I copied the h950p svg file, but the two buttons I added aren't recognized properly on the GNOME wacom tablet settings menu. The buttons I added show up, but don't work separately from each other. How can I go about fixing this?

The zip files include my current progress with the svg, .tablet, as well as a picture describing number 2.
[files.zip](https://github.com/linuxwacom/libwacom/files/6107948/files.zip)

**Comment by whot** [comment] 2021-03-11 01:57
The touch strip is [the horizontal bar at the top left](https://www.huion.com/pen_tablet/HS/huion-hs611.html)? tbh, I'm not sure how we'd do this one, and nothing in userspace right now supports this. To get this properly supported as a 4-bit touchstrip this should be wrapped in the tablet interface in libinput so we can change the button events to strip events. For now, I think just leaving it out with a comment in the file is the best approach, at least that way you get most of the tablet working.

For the svg file, did you run `ninja test` or `make check`? There's a svg verifier that should point out some of the more obvious things that can fail, otherwise it's unfortunately down to the [layout README](https://github.com/linuxwacom/libwacom/blob/master/data/layouts/README.md) which details the various requirements.

My guess right now is that one of the buttons doesn't have the right ID or class assigned.

**Comment by VoltageAmperage** [comment] 2021-04-22 00:43
I finally got some time to make progress and now everything is broken, unfortunately. 

It's still recognizing two tablets, both of them are listed in GNOME settings as Huion H950P tablets instead of HS611 (probably because they both have the same USB identifier, right?), but there aren't any buttons showing anymore when I click "Edit Buttons", nor can I map the tablet(s) to a single monitor. 

I tried copying the .tablet config file to /etc/libwacom and doing `sudo libwacom-update-db`, but it stays the same. I'm not sure where I'm getting stuck.

**Comment by whot** [comment] 2021-04-22 05:27
what's the output of `libwacom-list-local-devices` now? Ideally with the one from git. There are a few moving parts here, so we  need to narrow down where the issue is.

**Comment by VoltageAmperage** [comment] 2021-04-22 06:00
Yes, I've got the git repo installed at the moment. It says `Huion H950P: /dev/input/event26 /dev/input/event23 
Huion HS611: /dev/input/event24`.

If it's relevant at all, running `sudo evtest` shows that events 23, 24, and 26 are
`/dev/input/event23:	HUION Huion Tablet_HS611 Keyboard
/dev/input/event24:	       HUION Huion Tablet_HS611 Pen
/dev/input/event26:        HUION Huion Tablet_HS611 Pad`

So it's recognizing the pen as an HS611 pen, but it thinks the keyboard and the pad are for the Huion H950P?

**Comment by whot** [comment] 2021-04-22 06:47
can you *attach* the output of `libinput record` for each of those event nodes please? Also your current `.tablet` file for the 611 please.

**Comment by VoltageAmperage** [comment] 2021-04-22 07:05
Sure! Here are the `.yml` files and the `.tablet` file
[libinput-files.zip](https://github.com/linuxwacom/libwacom/files/6356208/libinput-files.zip)

It looks like the keyboard device is used for the multimedia keys, so I guess that doesn't really need to be configured.

**Comment by whot** [comment] 2021-04-22 07:29
please attach them separately next time, it takes 27 extra clicks to get to the data with a zip file and github is click-happy enough already.

So, your `.tablet` file current lists:
```
DeviceMatch=usb:256c:006d:HUION Huion Tablet_HS611 Pad
```
The part after the 006d is the name match - right now you're only matching on the pad itself. For `event23` it falls back to the next match which happens to be the 950 (by virtue of being first, I suspect). This should fix the issue:
```
DeviceMatch=usb:256c:006d:HUION Huion Tablet_HS611 Pad:usb:256c:006d:HUION Huion Tablet_HS611 Pen
```

**Comment by VoltageAmperage** [comment] 2021-04-22 07:54
So now `libwacom-list-local-devices` shows the pad and the pen being from the HS611, instead of the H950P, so that's fixed. Unfortunately it still refuses to map to a single monitor or allow me to assign any buttons at all. Is this a bug with GNOME 40?

**Comment by bigfatturd** [comment] 2021-04-22 17:54
Howdy, I have a kamvas pro 16 (kamvas 16 PRO, the branding is everywhere) model [GT-156](https://www.huion.com/pen_display/kamvas-pro-16.html). My real issue is that it no longer maps to it's display. Also got the reporting as a H950P like voltage (which I fixed by removing the H950P.) I also have the same USB IDs as the H950P and HS611. Oddest thing is, this tablet mapped to it's display until recently. Was definitely an update (currently on arch using gnome 40) I pulled my package list with version numbers with a ```pacman -Qn```, I do have some AUR installed packages, but they're related to my DAW.

Figured before I ran an update (it's probably been a good few days since.) I'd go ahead and make it work a bit more proper since it was showing up as a H950P, and didn't give me the option of calibrating (and lordy it could use it.)

Libinput only shows 2 events for my tablet (normal as far as I know, I've had it for a minute and could get it functioning without the touchbar, which I never use anyway, and it's always only ever had two events.)

I think the major stickler here is going to be that these huionsjust don't identify themselves properly to the kernel. Just ```HID 256c:006d Pen``` and Pad. So the only real way for some huion users to get it reporting right is just making their definitions themselves while deleting the H950P tablet file.

Voltage's evdev codes appear correct, although I know I need more, but I'm more concerned with getting the display mapped and getting calibration working. Saved some scrolling and filtered through the record on the pen to isolate what I think are the actual buttons if it matters. I don't get any errors when running libwacom-list-local-devices, but I did not run any of the ultiies because I'm a degenerate. I'll look into running them later.

[recordpad.txt](https://github.com/linuxwacom/libwacom/files/6360296/recordpad.txt)
[recordpen.txt](https://github.com/linuxwacom/libwacom/files/6360297/recordpen.txt)
[libwacomlldout.txt](https://github.com/linuxwacom/libwacom/files/6360325/libwacomlldout.txt)
[huion-gt-156.tablet.txt](https://github.com/linuxwacom/libwacom/files/6360306/huion-gt-156.tablet.txt)
[huion-gt-156.svg.txt](https://github.com/linuxwacom/libwacom/files/6360314/huion-gt-156.svg.txt)

I gotta get some z's so sorry if anything isn't in a format that works for you, take your time, need me to fix it and I will. I figured since there was an open related issue I might as well throw my input in since we're seeing a lot of the same things on both devices. I'm gonna run a -Syu and see what happens after a reboot.

**Comment by bigfatturd** [comment] 2021-04-22 18:16
Alright, had to jot this down. After reboot it is still using my config, but the display was also mapped appropriately. Despite the fact that in the gnome settings panel under wacom it was set to one of my displayport monitors. Changing that setting to HDMI-1 (the integrated display) pulled me out of my desktop session to an unresponsive tty, and eventually back to GDM with an also unresponsive login. It did let me back in at one point though.

the map buttons option also does not like my config, but I expected that. For anyone else with a huion tablet that is reading through this.

**Comment by whot** [comment] 2021-04-22 22:48
@VoltageAmperage: had another look at the `.tablet` file and only one comment on that: `Width` and `Height` are integers, in inches, just round to whatever marketing says (no-one uses this anyway afaik). The rest seems correct from libwacom's POV so I can only guess right now that it's the GNOME integration that's somewhat broken here.

Anything in the journal?

**Comment by VoltageAmperage** [comment] 2021-04-23 09:52
I used @bigfatturd 's solution and removed the H950P `.tablet` file, but unfortunately that only removed the keyboard device from showing in the settings menu, the pad still refuses to map to a screen or allow me to assign buttons.

@whot I rounded down the size to integers, so it's 10 inches by 6 inches now. What do you mean by journal? Is that `journalctl`? Sorry I'm fairly new to Linux.

**Comment by whot** [comment] 2021-04-27 04:47
yes, `journalctl` - that's where all the messages go. If mutter or gnome-control-center has some mapping issues likely the error messages show up in there. One option is to run `journalctl -ef` and then start the control-center, it's like `tail -f` on the journal. Otherwise... it's googling around for the exact commands because I can't always remember them myself.

**Comment by VoltageAmperage** [comment] 2021-05-01 08:16
There is an error that shows in the journal when I try to map the buttons in the control center, but not when I try to map to a display. I included that in the text file. I also included a snippet of what the journal shows when I plug in the tablet, but it doesn't seem like anything is out of the ordinary there. I suppose I can open an issue on GNOME's gitlab or something to see what's wrong, as it seems like it's on their side of things at the moment.

[tabletjournal.txt](https://github.com/linuxwacom/libwacom/files/6409129/tabletjournal.txt)

**Comment by whot** [comment] 2021-05-04 05:06
sorry, at this point I'm giving up. I think the `.tablet` file is fine and should be added, any mapping issues may be a gnome issue instead. Can you file a PR with the current tablet file please so we can get this merged?

**Comment by whot** [comment] 2022-08-03 03:14
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks

**Closed by whot** 2022-08-03 03:14 UTC
