### ISSUE TITLE
Null dereference

### ISSUE THREAD

**Issue by Mindavi** [linuxwacom/libwacom#378] opened 2021-03-19 09:56 UTC
I was compiling libwacom and got this warning:

```
In file included from /nix/store/sf9gz9ysshhg8d7cqc98l53hc941lch8-aarch64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0/aarch64-unknown-linux-gnu/sys-include/stdio.h:866,
                 from ../libwacom/libwacom.h:34,
                 from ../libwacom/libwacomint.h:34,
                 from ../libwacom/libwacom-database.c:32:
In function 'printf',
    inlined from 'libwacom_parse_tablet_keyfile' at ../libwacom/libwacom-database.c:658:4,
    inlined from 'load_tablet_files' at ../libwacom/libwacom-database.c:855:7,
    inlined from 'database_new_for_paths' at ../libwacom/libwacom-database.c:943:8:
/nix/store/sf9gz9ysshhg8d7cqc98l53hc941lch8-aarch64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0/aarch64-unknown-linux-gnu/sys-include/bits/stdio2.h:110:10: warning: '%s' directive argument is null [-Wformat-overflow=]
  110 |   return __printf_chk (__USE_FORTIFY_LEVEL - 1, __fmt, __va_arg_pack ());
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libwacom/libwacom-database.c: In function 'database_new_for_paths':
../libwacom/libwacom-database.c:658:26: note: format string is defined here
  658 |    DBG("failed to match '%s' for product/vendor IDs in '%s'\n", string_list[i], path);
      |                          ^~
```

I think this is something that needs fixing, since there's a loop just before that that runs until `string_list[i]` is NULL.

```
for (i = 0; string_list[i]; i++) {
        if (libwacom_matchstr_to_match (device, string_list[i]))
                nmatches++;
        if (nmatches == 1)
                first_valid_match = i;
}
if (nmatches == 0) {
        DBG("failed to match '%s' for product/vendor IDs in '%s'\n", string_list[i], path);
        g_strfreev (string_list);
        goto out;
}
```

That means that if a failure occurs, string_list[i] is NULL and should not be dereferenced / interpreted as string.

**Comment by whot** [comment] 2021-03-19 21:26
indeed, quick peek at the code suggests what was intended here was using `string_list` as the actual value from the config file (i.e. as string, not string list).  Want to submit a patch to fix this?

**Comment by whot** [comment] 2021-03-22 04:38
#380 has the fix for this now, turns out it wasn't a true NULL-dereference, `printf` usually handles a NULL string (it does with glibc anyway). So the error message was merely pointless, but not dangerous.

Fixed and immediately replaced with a more useful error message.

**Comment by Mindavi** [comment] 2021-03-22 18:53
Yeah, in most cases libc can be assumed, and other standard c libraries will in most cases handles this well too. Anyhow, it's better to have a useful message indeed :).

**Closed** 2021-03-23 21:31 UTC
