### ISSUE TITLE
Apps doesn't recognize Trust Flex Graphics Tablet stylus buttons 

### ISSUE THREAD

**Issue by RussianNeuroMancer** [linuxwacom/libwacom#63] opened 2019-01-25 12:56 UTC
Hello!

I trying to use Trust Flex Graphics Tablet with Krita, but find that I can not remap stylus buttons to Krita functions such as eraser and pop-up palette. According to @whot 

> pad buttons being BTN_FORWARD and BTN_EXTRA is not that uncommon, a client should be able to handle this. You will need a libwacom patch adding EvdevCodes to the tablet data file for this though

([source](https://gitlab.freedesktop.org/libinput/libinput/issues/64#note_8545))

It's seems like it should be possible to somehow solve this issue in libwacom? If so, is there examples of patches that add EvdevCodes and how I can write one myself?

**Comment by leerson** [comment] 2019-01-28 14:32
I have same Flex Design Tablet. To workaround bug bugzilla.kernel.org/show_bug.cgi?id=202195 I boot with Linux 4.17 kernel, but with this kernel buttons doesn't work in Krita, Gimp and AzPainter. How to make buttons work?

**Comment by whot** [comment] 2019-01-28 21:36
>  If so, is there examples of patches that add EvdevCodes and how I can write one myself?

easiest: `git grep EvdevCodes` in the source repo and then look at the `.tablet` files that come up. You can look up their history with `git log <filename>` and that gives you the commit that introduced it. You can use `evtest` or `evemu-record` to get at the event codes themselves.

**Comment by jigpu** [comment] 2019-01-28 21:56
Am I correct in understanding that the problem is with the buttons on the *pen*? Setting EvdevCodes wouldn't be the right action for a buggy pen, only a buggy pad, and it doesn't look like the Trust Flex even has a pad...

**Comment by whot** [comment] 2019-01-28 23:51
huh, right, this is an issue with the pen buttons, not the pad buttons. In that case libwacom can't do anything and this needs to be fixed in the kernel. Since there's another issue with the missing `BTN_TOOL_PEN` as well, I'm going to say the kernel needs to be fixed here first, see https://bugzilla.kernel.org/show_bug.cgi?id=202195

**Closed by whot** 2019-01-28 23:51 UTC
