### ISSUE TITLE
Regression : Random disconnection with wired XBox360 gamepad (original Microsoft)

### ISSUE THREAD

**Issue by Sh33n** [linuxwacom/libwacom#434] opened 2021-10-28 13:44 UTC
Hello,

I'm running Arch, 5.10.75-1-lts kernel, cinnamon desktop environment, and since a few weeks, my wired xbox360 gamepad is randomly disconnected when playing, it can happen every 5 minutes and it's annoying.
I'm mostly using it with Steam, Lutris, and emulators (Cemu and Yuzu).

Kernel message : 

[  990.145519] usb 1-13: USB disconnect, device number 2
[  990.145788] xpad 1-13:1.0: xpad_try_sending_next_out_packet - usb_submit_urb failed with result -19
[  990.631373] usb 1-13: new full-speed USB device number 3 using xhci_hcd
[  991.017960] usb 1-13: New USB device found, idVendor=045e, idProduct=028e, bcdDevice= 1.14
[  991.017966] usb 1-13: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  991.017969] usb 1-13: Product: Controller
[  991.017971] usb 1-13: Manufacturer: ©Microsoft Corporation
[  991.017972] usb 1-13: SerialNumber: 0F98F1A
[  991.036822] input: Microsoft X-Box 360 pad as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-13/1-13:1.0/input/input32
[ 3540.426205] usb 1-13: USB disconnect, device number 3
[ 3540.426417] xpad 1-13:1.0: xpad_try_sending_next_out_packet - usb_submit_urb failed with result -19
[ 3540.989682] usb 1-13: new full-speed USB device number 4 using xhci_hcd
[ 3541.385189] usb 1-13: New USB device found, idVendor=045e, idProduct=028e, bcdDevice= 1.14
[ 3541.385193] usb 1-13: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3541.385195] usb 1-13: Product: Controller
[ 3541.385196] usb 1-13: Manufacturer: ©Microsoft Corporation
[ 3541.385197] usb 1-13: SerialNumber: 0F98F1A

After a few research, I've found this post saying it was related with libwacom : https://bbs.archlinux.org/viewtopic.php?id=256943

So I've downgrade my libwacom 1.12 to 1.11.
And all seems to work properly now.

I think the 1.12 commit made a regression for this gamepad, I'm not developer so I can't tell you more.
If your need further information, just ask.

Thanks.

**Comment by whot** [comment] 2021-11-08 03:47
libwacom is just a bunch of text files with a C api to read those. It doesn't do anything on its own with the device and even the few users of libwacom (GNOME and libinput, basically) merely use it to get information about the device the kernel doesn't provide. Things like "is this tablet integrated into the screen" for example.

libwacom *cannot* be responsible for the usb errors you're seeing.

There's a minor chance that cca42a8508506f150380f452141ce02787919b0a is a regression if somehow steam requires that that udev property is set. But I'm struggling to see how since we don't have any entries for microsoft devices and thus that commit shouldn't have any effect. So, tbh, I think the libwacom bit here is a red herring, something else is going on.

**Comment by whot** [comment] 2022-08-03 03:03
closing after 10 months

**Closed by whot** 2022-08-03 03:03 UTC
