### ISSUE TITLE
Even with isdv4-4870.tablet in place, Wacom panel in Gnome Control Center detect tablet (HP Elite x2 1013 G3) but not stylus (HP Active Pen G2)

### ISSUE THREAD

**Issue by RussianNeuroMancer** [linuxwacom/libwacom#149] opened 2019-08-25 07:15 UTC
Hello!

I trying to get Gnome Control Center recognize not only tablet but also stylus. To achieve that I placed [isdv4-4870.tablet](https://github.com/linuxwacom/libwacom/blob/a3ae00e0b845676067b91dce710b0fe576ca8088/data/isdv4-4870.tablet) to [/usr/share/libwacom/](https://packages.ubuntu.com/eoan/all/libwacom-common/filelist) manually, since [libwacom 0.33 is not available in Ubuntu](https://launchpad.net/ubuntu/+source/libwacom) yet. 

In result tablet part is detected in Gnome Control Center as "Wacom ISDv4 4870" tablet, but stylus is still not detected at all, even if it near the screen (and was used to open up Gnome Control Center).

Is it libwacom issue or Gnome Control Center issue?

**Comment by jigpu** [comment] 2019-09-03 20:27
Likely a duplicate of issue #57. Please use our [capture.sh script](https://gist.githubusercontent.com/jigpu/b7b47e4bede584cec8562f666fd84af4/raw/af36c0a0fc2c019750472443369915ad7ea97737/capture.sh) to record a single stroke with the pen and then attach the generated tarball here. We will likely need to create a stylus definition for you.

**Comment by RussianNeuroMancer** [comment] 2019-09-04 18:37
Thank you for looking into this issue!

Attached: [record_1567622140.tar.gz](https://github.com/linuxwacom/libwacom/files/3575991/record_1567622140.tar.gz)

**Comment by jigpu** [comment] 2019-09-05 17:57
Looks like the ID for your pen is 0x806B. Try adding the following lines to your `/usr/share/libwacom/libwacom.stylus` file:
~~~
[0x806B]
Name=HP AES Pen
Buttons=2
HasEraser=true
Axes=Tilt;Pressure
Type=General
~~~

And the following line in the `[Device]` section of your `/usr/share/libwacom/isdv4-4870.tablet` file:
~~~
Styli=0x806B
~~~

With any luck, the pen will show up in the GNOME Control Center after rebooting and bringing the pen into prox over its window.

**Comment by RussianNeuroMancer** [comment] 2019-09-06 13:06
@jigpu, thank you! Yes, it's helps. 

There is recording of Dell Active Pen PN557W which is not detected as well: 
[record_1567774749.tar.gz](https://github.com/linuxwacom/libwacom/files/3584001/record_1567774749.tar.gz) (however, I record it on same tablet, i.e. HP Elite x2 1013 G3 - is this record still useful, or it should be done specifically on device this stylus was intended for?)

Also I noticed Gnome Control Center doesn't allow enabling of same behaviour as with Wacom Windows drivers - ability to perform scrolling with stylus (currently default in Windows 10). Is this Linux driver limitation, Mutter limitation or Gnome Control Center limitation?

**Comment by jigpu** [comment] 2019-09-06 15:50
For the second pen, please make the following additions to `/usr/share/libwacom/libwacom.stylus`:
~~~
[0x231]
Name=Dell AES Pen
Buttons=2
HasEraser=true
Axes=Tilt;Pressure
Type=General
~~~
And change the "Styli" line I had you add to the `[Device]` section of `/usr/share/libwacom/isdv4-4870.tablet` to instead be:
~~~
Styli=0x806B;0x231
~~~

**Comment by jigpu** [comment] 2019-09-06 15:52
> Also I noticed Gnome Control Center doesn't allow enabling of same behaviour as with Wacom Windows drivers - ability to perform scrolling with stylus (currently default in Windows 10). Is this Linux driver limitation, Mutter limitation or Gnome Control Center limitation?

Recent versions of the Linux driver have a pan-scrolling function where you can press a button and drag the tip up and down the screen to scroll. The GNOME Control Center doesn't expose this functionality right now. To enable panscroll, try running the following command:

~~~
xsetwacom set <stylus_id> button 2 pan
~~~

Alternatively, you can have the second button (normally treated as an eraser by tablet PC pens) instead perform pan-scroll by running:

~~~
xsetwacom set <eraser_id> button 1 pan
~~~

**Comment by RussianNeuroMancer** [comment] 2019-09-06 17:27
> For the second pen, please make the following additions to /usr/share/libwacom/libwacom.stylus

Thanks, it's detected, even without editing isdv4-4870.tablet (which I guess is how it's supposed to be because one could use one Wacom stylus with many Wacom-compatible tablets - is my understanding is correct?) 

> Recent versions of the Linux driver have a pan-scrolling function where you can press a button and drag the tip up and down the screen to scroll. 

Do you mean kernel driver or xorg driver? In case of Wayland session this should be implemented in libinput, right? (I asking about Wayland session because on x86 tablets Wayland session currently is much more useful than X11 session.)

**Comment by jigpu** [comment] 2019-09-06 18:07
> Thanks, it's detected, even without editing isdv4-4870.tablet (which I guess is how it's supposed to be because one could use one Wacom stylus with many Wacom-compatible tablets - is my understanding is correct?)

One stylus will typically be compatible with multiple tablets, but there will definitely be tablets that it doesn't work with. The "Styli" line defines those compatibility relationships. I assumed that GNOME required the Styli list to include each compatible pen, but that must not be the case based on your observation. The fact that the pen works must be enough of a compatibility indicator for them :D

> Do you mean kernel driver or xorg driver? In case of Wayland session this should be implemented in libinput, right? (I asking about Wayland session because on x86 tablets Wayland session currently is much more useful than X11 session.)

The pan-scrolling feature is a part of the Xorg driver. For Wayland, the functionality would need to be implemented in the compositor (i.e., Mutter). You should open a feature request at https://gitlab.gnome.org/GNOME/mutter/issues/ if you'd like to see it.

I haven't given Wayland a thorough test-drive in a while, but its good to hear that its improving -- I remember back when Fedora first turned it on by default and we got loads of bug reports that we had to refer to the GNOME team.

**Comment by RussianNeuroMancer** [comment] 2019-09-06 18:31
> You should open a feature request at https://gitlab.gnome.org/GNOME/mutter/issues/ if you'd like to see it.

Ok, [done](https://gitlab.gnome.org/GNOME/mutter/issues/766).

Once again thank you for help with this issue :)

**Closed** 2019-09-10 00:24 UTC
Labels: enhancement

**Comment by RussianNeuroMancer** [comment] 2019-09-10 06:11
Sorry to bother you, @jigpu. Just to be sure: both of HP Active Pen G2 and Dell Active Pen PN557W will be added to libwacom.stylus in next version of libwacom?
